# Generated by Django 3.1.5 on 2021-03-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Завпрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(verbose_name='Запрос'),
        ),
    ]
